### ISSUE TITLE
Click noise at beginning (Harry Potter and the Goblet of Fire; GAX 3.05A)

### ISSUE THREAD

**Issue by loveemu** [loveemu/gaxtapper#1]
* Commit hash: 7c7439a7 ([download](https://ci.appveyor.com/project/loveemu/gaxtapper/builds/39189376/job/2dlno5b68ynr5n43))
* Game: Harry Potter and the Goblet of Fire (USA) (sha1: 951f311d9a99920abdbb9134ac8b9d00dfdb9b0b)
* Song: CS_GBA_Cutscenes_03, and others
* Player: GSF Decoder (foo_input_gsf) 3.0.21
    * Does not reproduce in mGBA 0.9.1 and the latest development version: 7006-86ec2d4
    * Does not reproduce in GSF Decoder (foo_input_gsf) 3.0.19

**Comment by loveemu** [comment]
I think the driver needs to be improved, but the cause is not clear yet.

**Comment by loveemu** [comment]
Since it is most likely a problem with foo_input_gsf, I sent a message to kode54 on Discord.

**Comment by kode54** [comment]
This should be fixed now. I somehow screwed up my Windows dev machines and didn't re-pull my copy of libmgba there, to remove bad commits from a "fix" I attempted which "fixed" a broken rip of Metroid: Zero Mission, but apparently breaks a whole load of proper rips.

**Comment by loveemu** [comment]
Fixed at foo_input_gsf 3.0.22
